remote_theme: pages-themes/midnight@v0.2.0
title: PopTracker
description: powerful open progress tracker
show_downloads: false
repo: "black-sliver/PopTracker"
keep_files:
  - schema
plugins:
  - jekyll-remote-theme
sass:
  style: compressed
